name: CI/CD testing for Vite React App

on:
  workflow_dispatch:
  push:
    branches: [master]

# permissions:
  # contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      packages: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Node
      uses: actions/setup-node@v3
      with:
        node-version: 22

    # - name: Install dependencies
    #   run: npm i -D
    - run: npm install --save --save-dev
    - run: npm run build

    # - name: Run tests
      # run: npm test # or your test command

    # - name: Deploy to VPS via SSH
    #   uses: appleboy/ssh-action@v1.0.3
    #   with:
    #     host: ${{ secrets.VPS_HOST }}
    #     username: ${{ secrets.VPS_USER }}
    #     key: ${{ secrets.VPS_SSH_KEY }}
    #     port: 22
    #     script: |
    #       cd /path/to/your/project
    #       git pull origin master
    #       npm install
    #       npm run build
    #       pm2 restart your-app-name







    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push container to GHCR
      uses: docker/build-push-action@v5
      with:
          context: .
          platforms: linux/amd64
          push: true
          tags: |
              ghcr.io/${{ github.repository_owner }}/react-vite-docker-tailscale:latest

    - name: Connect Tailscale
      uses: tailscale/github-action@v2
      with:
        oauth-client-id: ${{ secrets.TS_CLIENT_ID }}
        oauth-secret: ${{ secrets.TS_CLIENT_SECRET }}
        tags: tag:homeserver-github-ci

    - name: Do the deploy thing
      run: |
        ssh -o "StrictHostKeyChecking no" root@100.89.122.24 "
          cd /manual-compose/test-react-tailscale
          docker compose pull
          docker compose up -d
        "