name: CI/CD testing for Vite React App

on:
  workflow_dispatch:
  push:
    branches: [master]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      packages: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Node
      uses: actions/setup-node@v3
      with:
        node-version: 22

    - name: Install dependencies
      run: npm ci

    # - name: Run Tests
    #   run: npm run test
    
    - name: Build project
      run: npm run build

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push container to GHCR
      uses: docker/build-push-action@v5
      with:
          context: .
          platforms: linux/amd64
          push: true
          tags: |
              ghcr.io/${{ github.repository_owner }}/react-vite-docker-tailscale:latest

    - name: Install and Connect via Tailscale CLI
      env:
        TS_AUTHKEY: ${{ secrets.TS_AUTHKEY }}
        TS_HOME_SERVER_USER: ${{ vars.TS_HOME_SERVER_USER }}
        TS_HOME_SERVER_IP: ${{ vars.TS_HOME_SERVER_IP }}
        TS_HOME_SERVER_PROJECT_DIR: ${{ vars.TS_HOME_SERVER_PROJECT_DIR }}
      run: |
        curl -fsSL https://pkgs.tailscale.com/stable/ubuntu/noble.noarmor.gpg | sudo tee /usr/share/keyrings/tailscale-archive-keyring.gpg >/dev/null
        curl -fsSL https://pkgs.tailscale.com/stable/ubuntu/noble.tailscale-keyring.list | sudo tee /etc/apt/sources.list.d/tailscale.list

        sudo apt-get update
        sudo apt-get install -y tailscale

        tailscale version

        echo $TS_AUTHKEY
        sudo tailscale up --auth-key=${TS_AUTHKEY} --hostname=gh-runner --advertise-tags=tag:homeserver-github-ci --ssh

        tailscale status
        tailscale ip

        tailscale ssh ${TS_HOME_SERVER_USER}@${TS_HOME_SERVER_IP} "mkdir -p ${TS_HOME_SERVER_PROJECT_DIR}"
        cat docker-compose.yml | tailscale ssh ${TS_HOME_SERVER_USER}@${TS_HOME_SERVER_IP} "cat > ${TS_HOME_SERVER_PROJECT_DIR}/docker-compose.yml"

        tailscale ssh ${TS_HOME_SERVER_USER}@${TS_HOME_SERVER_IP} <<'EOF'
          cd ${TS_HOME_SERVER_PROJECT_DIR}
          docker compose pull
          docker compose up -d
        EOF
