name: CI/CD testing for Vite React App

on:
  workflow_dispatch:
  push:
    branches: [master]

# permissions:
  # contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    # runs-on: self-hosted

    permissions:
      contents: read  # ChatGPT suggestion
      packages: write

    steps:
    - name: Ubuntu version
      run: lsb_release -a

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Node
      uses: actions/setup-node@v3
      with:
        node-version: 22
    - run: npm install --save --save-dev
    - run: npm run build

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push container to GHCR
      uses: docker/build-push-action@v5
      with:
          context: .
          platforms: linux/amd64
          push: true
          tags: |
              ghcr.io/${{ github.repository_owner }}/react-vite-docker-tailscale:latest

    # ChatGPT suggestion START >>>
    - name: Install Tailscale CLI
      run: |
        curl -fsSL https://pkgs.tailscale.com/stable/ubuntu/noble.noarmor.gpg | sudo tee /usr/share/keyrings/tailscale-archive-keyring.gpg >/dev/null
        curl -fsSL https://pkgs.tailscale.com/stable/ubuntu/noble.tailscale-keyring.list | sudo tee /etc/apt/sources.list.d/tailscale.list

        sudo apt-get update
        sudo apt-get install tailscale

        tailscale version

    - name: Connect to Tailscale (with SSH support)
      env:
        TS_AUTHKEY: ${{ secrets.TS_AUTHKEY }}
      run: |
        echo $TS_AUTHKEY
        sudo tailscale up --auth-key=${TS_AUTHKEY} --hostname=gh-runner --advertise-tags=tag:homeserver-github-ci --ssh

    - name: Show Tailscale connection
      run: |
        tailscale status
        tailscale ip
    
    - name: Deploy via Tailscale SSH
      run: |
        tailscale ssh root@100.89.122.24 <<'EOF'
          cd /manual-compose/test-react-tailscale
          docker compose pull
          docker compose up -d
        EOF
    # ChatGPT suggestion END <<<


    # - name: Connect Tailscale
    #   uses: tailscale/github-action@v2
    #   with:
    #     oauth-client-id: ${{ secrets.TS_CLIENT_ID }}
    #     oauth-secret: ${{ secrets.TS_CLIENT_SECRET }}
    #     tags: tag:homeserver-github-ci

    # # - name: Do the deploy thing
    # #   run: |
    # #     ssh -o "StrictHostKeyChecking no" root@100.89.122.24 "
    # #       cd /manual-compose/test-react-tailscale
    # #       docker compose pull
    # #       docker compose up -d
    # #     "
    
    # - name: testing ssh connection and deploy
    #   uses: appleboy/ssh-action@master
    #   with:
    #     host: 100.89.122.24
    #     username: root
    #     key: ${{ secrets.HS_SSH_SECRET }}
    #     port: 22
    #     script: |
    #       cd /manual-compose/test-react-tailscale
    #       docker compose pull
    #       docker compose up -d